In [1]:
#  Cargar datos de entrenamiento
import pandas as pd  #  type: ignore

train_data = pd.read_csv(
    "../files/input/train_data.csv.zip",
    #index_col=False,
    compression="zip",
)


#  Cargar datos de prueba
import pandas as pd  #  type: ignore

test_data = pd.read_csv(
    "../files/input/test_data.csv.zip",
    #index_col=False,
    compression="zip",
)

In [2]:
train_data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,10748,310000,1,3,1,32,0,0,0,0,...,84373,57779,14163,8295,6000,4000,3000,1000,2000,0
1,12574,10000,2,3,1,49,-1,-1,-2,-1,...,1690,1138,930,0,0,2828,0,182,0,1
2,29677,50000,1,2,1,28,-1,-1,-1,0,...,45975,1300,43987,0,46257,2200,1300,43987,1386,0
3,8857,80000,2,3,1,52,2,2,3,3,...,40748,39816,40607,3700,1600,1600,0,1600,1600,1
4,21099,270000,1,1,2,34,1,2,0,0,...,22448,15490,17343,0,4000,2000,0,2000,2000,0

In [3]:
test_data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
1,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,13912,0,0,0,13007,1122,0,0
2,11,200000,2,3,2,34,0,0,2,0,...,2513,1828,3731,2306,12,50,300,3738,66,0
3,15,250000,1,1,2,29,0,0,0,0,...,59696,56875,55512,3000,3000,3000,3000,3000,3000,0
4,16,50000,2,3,3,23,1,2,0,0,...,28771,29531,30211,0,1500,1100,1200,1300,1100,0

In [4]:
# Paso 1.
# Realice la limpieza de los datasets:
# - Renombre la columna "default payment next month" a "default".
# - Remueva la columna "ID".
# - Elimine los registros con informacion no disponible.
# - Para la columna EDUCATION, valores > 4 indican niveles superiores
#   de educaciÃ³n, agrupe estos valores en la categorÃ­a "others".
#
# Renombre la columna "default payment next month" a "default"
# y remueva la columna "ID".

# Paso 1: Limpieza de datos
# Renombrar la columna objetivo y eliminar 'ID'
train_data.rename(columns={"default payment next month": "default"}, inplace=True)
test_data.rename(columns={"default payment next month": "default"}, inplace=True)

train_data.drop(columns=["ID"], inplace=True)
test_data.drop(columns=["ID"], inplace=True)

# Eliminar registros con valores faltantes
train_data.dropna(inplace=True)
test_data.dropna(inplace=True)
test_data.isna().sum()

# Agrupar valores > 4 en EDUCATION como 'otros'
#train_data["EDUCATION"] = train_data["EDUCATION"].apply(lambda x: x if x <= 4 else 4)
#test_data["EDUCATION"] = test_data["EDUCATION"].apply(lambda x: x if x <= 4 else 4)

df = test_data.loc[(test_data["EDUCATION"] != 0)]
df = test_data.loc[(test_data["MARRIAGE"] != 0)]
df.loc[test_data["EDUCATION"] > 4, "EDUCATION"] = 4

df = train_data.loc[(train_data["EDUCATION"] != 0)]
df = train_data.loc[(train_data["MARRIAGE"] != 0)]
df.loc[train_data["EDUCATION"] > 4, "EDUCATION"] = 4
#
print(train_data.head())

   LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0     310000    1          3         1   32      0      0      0      0
1      10000    2          3         1   49     -1     -1     -2     -1
2      50000    1          2         1   28     -1     -1     -1      0
3      80000    2          3         1   52      2      2      3      3
4     270000    1          1         2   34      1      2      0      0

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...      84373      57779      14163      8295      6000      4000
1      2  ...       1690       1138        930         0         0      2828
2     -1  ...      45975       1300      43987         0     46257      2200
3      3  ...      40748      39816      40607      3700      1600      1600
4      2  ...      22448      15490      17343         0      4000      2000

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default
0      3000      1000      2000        0
1         0       182         0        1
2      1300     43987      1386        0
3         0      1600      1600        1
4         0      2000      2000        0

[5 rows x 24 columns]

C:\Users\danil\AppData\Local\Temp\ipykernel_29736\4281160209.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[test_data["EDUCATION"] > 4, "EDUCATION"] = 4
C:\Users\danil\AppData\Local\Temp\ipykernel_29736\4281160209.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[train_data["EDUCATION"] > 4, "EDUCATION"] = 4

In [5]:
# Paso 2: Dividir los datasets en x_train, y_train, x_test, y_test
x_train = train_data.drop(columns=["default"], axis=1)
y_train = train_data["default"]

x_test = test_data.drop(columns=["default"], axis=1)
y_test = test_data["default"]

In [6]:
# Paso 3.
# Cree un pipeline para el modelo de clasificaciÃ³n. Este pipeline debe
# contener las siguientes capas:
# - Transforma las variables categoricas usando el mÃ©todo
#   one-hot-encoding.
# - Escala las demas variables al intervalo [0, 1].
# - Selecciona las K mejores caracteristicas.
# - Ajusta un modelo de regresion logistica.
#

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer

# Paso 3: Crear el pipeline
# Definir las columnas categÃ³ricas y numÃ©ricas
categorical_features = ["SEX", "EDUCATION", "MARRIAGE"]
numeric_features = [col for col in x_train.columns if col not in categorical_features]

# Crear los transformadores para las columnas categÃ³ricas y numÃ©ricas
categorical_transformer = OneHotEncoder(handle_unknown="ignore")
numeric_transformer = MinMaxScaler()

# Crear el preprocesador usando ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ]
)

# Crear el pipeline con el preprocesador, selector de caracterÃ­sticas y modelo
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("feature_selection", SelectKBest(score_func=f_classif)),
        ("classifier", LogisticRegression(max_iter=1000, random_state=42)),
    ]
)

# Ajustar el pipeline a los datos de entrenamiento
pipeline.fit(x_train, y_train)

# Predecir con el pipeline ajustado
y_pred = pipeline.predict(x_test)

print(y_pred)

# evalura el modelo en conjuto de prueba

print(pipeline.score(x_test, y_test))

[0 0 0 ... 0 1 0]
0.8205555555555556

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, balanced_accuracy_score

# Paso 4.
# Optimice los hiperparametros del pipeline usando validaciÃ³n cruzada.
# Use 10 splits para la validaciÃ³n cruzada. Use la funciÃ³n de precision
# balanceada para medir la precisiÃ³n del modelo.

# Definir el espacio de bÃºsqueda de hiperparÃ¡metros
param_grid = {
    'feature_selection__k': [1, 10, 20, 30],
    'classifier__C': [0.6],
}
# Crear el objeto GridSearchCV con validaciÃ³n cruzada de 10 splits
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=10,
    scoring=make_scorer(balanced_accuracy_score), n_jobs=-1
)

# Ajustar el GridSearchCV a los datos de entrenamiento
grid_search.fit(x_train, y_train)

# Obtener los mejores hiperparÃ¡metros
best_params = grid_search.best_params_
print("Mejores hiperparÃ¡metros:", best_params)

# Predecir con el mejor modelo
best_model = grid_search.best_estimator_
y_pred_optimized = best_model.predict(x_test)

Mejores hiperparÃ¡metros: {'classifier__C': 0.6, 'feature_selection__k': 1}

In [8]:
#mostrar los mejores parametros
print(best_params)

{'classifier__C': 0.6, 'feature_selection__k': 1}

In [9]:

# Paso 5.
# Guarde el modelo (comprimido con gzip) como "files/models/model.pkl.gz".
# Recuerde que es posible guardar el modelo comprimido usanzo la libreria gzip.

import gzip
import pickle
import os

# Paso 5: Guardar el modelo
os.makedirs('../files/models', exist_ok=True)
with gzip.open('../files/models/model.pkl.gz', 'wb') as file:
    pickle.dump(grid_search, file)  # Guardar el objeto GridSearchCV completo

In [10]:
# Paso 6.
# Calcule las metricas de precision, precision balanceada, recall,
# y f1-score para los conjuntos de entrenamiento y prueba.
# Guardelas en el archivo files/output/metrics.json. Cada fila
# del archivo es un diccionario con las metricas de un modelo.
# Este diccionario tiene un campo para indicar si es el conjunto
# de entrenamiento o prueba. Por ejemplo:
#
# {'type': 'metrics', 'dataset': 'train', 'precision': 0.8, 'balanced_accuracy': 0.7, 'recall': 0.9, 'f1_score': 0.85}
# {'type': 'metrics', 'dataset': 'test', 'precision': 0.7, 'balanced_accuracy': 0.6, 'recall': 0.8, 'f1_score': 0.75}

# Calcular mÃ©tricas para el conjunto de entrenamiento

from sklearn.metrics import precision_score, recall_score, f1_score, balanced_accuracy_score
import json

y_train_pred = best_model.predict(x_train)
train_metrics = {
    'type': 'metrics',
    'dataset': 'train',
    'precision': precision_score(y_train, y_train_pred),
    'balanced_accuracy': balanced_accuracy_score(y_train, y_train_pred),
    'recall': recall_score(y_train, y_train_pred),
    'f1_score': f1_score(y_train, y_train_pred)
}

# Calcular mÃ©tricas para el conjunto de prueba
test_metrics = {
    'type': 'metrics',
    'dataset': 'test',
    'precision': precision_score(y_test, y_pred_optimized),
    'balanced_accuracy': balanced_accuracy_score(y_test, y_pred_optimized),
    'recall': recall_score(y_test, y_pred_optimized),
    'f1_score': f1_score(y_test, y_pred_optimized)
}

# Guardar las mÃ©tricas en un archivo JSON
import os

# Crear el directorio si no existe
os.makedirs('../files/output', exist_ok=True)

metrics = [train_metrics, test_metrics]
with open('../files/output/metrics.json', 'w') as f:
    json.dump(metrics, f, indent=4)

# ver metricas

print(metrics)

[{'type': 'metrics', 'dataset': 'train', 'precision': 0.6932966023875115, 'balanced_accuracy': np.float64(0.6391959574465568), 'recall': 0.31944150624074463, 'f1_score': 0.4373642288196959}, {'type': 'metrics', 'dataset': 'test', 'precision': 0.7006302521008403, 'balanced_accuracy': np.float64(0.654602898974264), 'recall': 0.3493975903614458, 'f1_score': 0.46627053477804964}]

In [11]:
# Paso 7.
# Calcule las matrices de confusion para los conjuntos de entrenamiento y
# prueba. Guardelas en el archivo files/output/metrics.json. Cada fila
# del archivo es un diccionario con las metricas de un modelo.
# de entrenamiento o prueba. Por ejemplo:
#
# {'type': 'cm_matrix', 'dataset': 'train', 'true_0': {"predicted_0": 15562, "predicte_1": 666}, 'true_1': {"predicted_0": 3333, "predicted_1": 1444}}
# {'type': 'cm_matrix', 'dataset': 'test', 'true_0': {"predicted_0": 15562, "predicte_1": 650}, 'true_1': {"predicted_0": 2490, "predicted_1": 1420}}

from sklearn.metrics import confusion_matrix

# Calcular la matriz de confusiÃ³n para el conjunto de entrenamiento
cm_train = confusion_matrix(y_train, y_train_pred)
cm_train_dict = {
    'type': 'cm_matrix',
    'dataset': 'train',
    'true_0': {"predicted_0": int(cm_train[0, 0]), "predicted_1": int(cm_train[0, 1])},
    'true_1': {"predicted_0": int(cm_train[1, 0]), "predicted_1": int(cm_train[1, 1])}
}

# Calcular la matriz de confusiÃ³n para el conjunto de prueba
cm_test = confusion_matrix(y_test, y_pred_optimized)
cm_test_dict = {
    'type': 'cm_matrix',
    'dataset': 'test',
    'true_0': {"predicted_0": int(cm_test[0, 0]), "predicted_1": int(cm_test[0, 1])},
    'true_1': {"predicted_0": int(cm_test[1, 0]), "predicted_1": int(cm_test[1, 1])}
}

# Leer las mÃ©tricas existentes del archivo JSON
with open('../files/output/metrics.json', 'r') as f:
    metrics = json.load(f)

# Agregar las matrices de confusiÃ³n a las mÃ©tricas
metrics.append(cm_train_dict)
metrics.append(cm_test_dict)

# Guardar las mÃ©tricas actualizadas en el archivo JSON
with open('../files/output/metrics.json', 'w') as f:
    json.dump(metrics, f, indent=4)

# Ver matrices de confusiÃ³n
print(cm_train_dict)
print(cm_test_dict)

{'type': 'cm_matrix', 'dataset': 'train', 'true_0': {'predicted_0': 15605, 'predicted_1': 668}, 'true_1': {'predicted_0': 3217, 'predicted_1': 1510}}
{'type': 'cm_matrix', 'dataset': 'test', 'true_0': {'predicted_0': 6806, 'predicted_1': 285}, 'true_1': {'predicted_0': 1242, 'predicted_1': 667}}

In [12]:
# Paso 6: Calcular mÃ©tricas para los conjuntos de entrenamiento y prueba
y_train_pred = best_model.predict(x_train)
train_metrics = {
    "type": "metrics",
    "dataset": "train",
    "precision": precision_score(y_train, y_train_pred),
    "balanced_accuracy": balanced_accuracy_score(y_train, y_train_pred),
    "recall": recall_score(y_train, y_train_pred),
    "f1_score": f1_score(y_train, y_train_pred)
}

test_metrics = {
    "type": "metrics",
    "dataset": "test",
    "precision": precision_score(y_test, y_pred_optimized),
    "balanced_accuracy": balanced_accuracy_score(y_test, y_pred_optimized),
    "recall": recall_score(y_test, y_pred_optimized),
    "f1_score": f1_score(y_test, y_pred_optimized)
}

# Paso 7: Calcular matrices de confusiÃ³n
cm_train = confusion_matrix(y_train, y_train_pred)
cm_train_dict = {
    "type": "cm_matrix",
    "dataset": "train",
    "true_0": {"predicted_0": int(cm_train[0, 0]), "predicted_1": int(cm_train[0, 1])},
    "true_1": {"predicted_0": int(cm_train[1, 0]), "predicted_1": int(cm_train[1, 1])}
}

cm_test = confusion_matrix(y_test, y_pred_optimized)
cm_test_dict = {
    "type": "cm_matrix",
    "dataset": "test",
    "true_0": {"predicted_0": int(cm_test[0, 0]), "predicted_1": int(cm_test[0, 1])},
    "true_1": {"predicted_0": int(cm_test[1, 0]), "predicted_1": int(cm_test[1, 1])}
}

# Guardar las mÃ©tricas y matrices en formato JSON
os.makedirs('../files/output', exist_ok=True)
with open('../files/output/metrics.json', 'w') as f:
    for entry in [train_metrics, test_metrics, cm_train_dict, cm_test_dict]:
        f.write(json.dumps(entry) + "\n")

# Ver mÃ©tricas y matrices de confusiÃ³n
print(train_metrics)
print(test_metrics)
print(cm_train_dict)
print(cm_test_dict)

{'type': 'metrics', 'dataset': 'train', 'precision': 0.6932966023875115, 'balanced_accuracy': np.float64(0.6391959574465568), 'recall': 0.31944150624074463, 'f1_score': 0.4373642288196959}
{'type': 'metrics', 'dataset': 'test', 'precision': 0.7006302521008403, 'balanced_accuracy': np.float64(0.654602898974264), 'recall': 0.3493975903614458, 'f1_score': 0.46627053477804964}
{'type': 'cm_matrix', 'dataset': 'train', 'true_0': {'predicted_0': 15605, 'predicted_1': 668}, 'true_1': {'predicted_0': 3217, 'predicted_1': 1510}}
{'type': 'cm_matrix', 'dataset': 'test', 'true_0': {'predicted_0': 6806, 'predicted_1': 285}, 'true_1': {'predicted_0': 1242, 'predicted_1': 667}}